[theme]
primaryColor="#00D084"
backgroundColor="#1A1A1A"
secondaryBackgroundColor="#2D2D2D"
textColor="#FFFFFF"
font="monospace"

[server]
headless = true
port = 8502

[browser]
gatherUsageStats = false
