[theme]
primaryColor="#0071E3"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F5F5F7"
textColor="#1D1D1F"
font="sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
